import '../assets/styles/globals.scss'
import { Roboto_Flex } from 'next/font/google'
import Providers from '../store/providers'

const roboto = Roboto_Flex({ subsets: ['latin'], variable: '--font-roboto' })

export const metadata = {
  title: 'Create Next Auth App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${roboto.className} ${roboto.variable}`}>
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
